.TH BOOKMARKCTL 1 "Dec 01, 2024" 0.1.0 "BookmarkFS User Manual"
.
.SH NAME
bookmarkctl - manage a mounted BookmarkFS filesystem
.
.SH SYNOPSIS
.B bookmarkctl
.I subcmd
.RI [ args ]
.PP
.B "bookmarkctl permd"
.RI [ options ]
.I name1
.I name2
.I pathname
.PP
.B "bookmarkctl fsck"
.I pathname
.PP
.B "bookmarkctl help"
.PP
.B "bookmarkctl version"
.
.SH DESCRIPTION
The
.B bookmarkctl
program is a command-line wrapper for various I/O controls of a BookmarkFS
filesystem.
.SS Permute directory entries
The
.B permd
sub-command re-arranges the order of the directory entries to be returned
from future
.BR readdir (3)
calls.
.PP
The
.I pathname
argument is the path to the directory.
The
.I name1
and
.I name2
arguments are filenames under that directory.
.SS Filesystem check
The
.B fsck
sub-command displays a list of filesystem errors found under the directory
referred to by
.IR pathname .
It does not recurse into subdirectories.
.PP
For the full fsck functionalities, use
.BR fsck.bookmarkfs (1).
.
.SH OPTIONS
.SS Permute directory entries
.TP
.B \-s
Exchange the positions of the directory entries represented by
.I name1
and
.IR name2 .
.TP
.BR \-b ", " \-a
Move the directory entry represented by
.I name1
to the position just before/after the one represented by
.IR name2 .
.PP
The
.BR \-s ", " \-b
and
.B \-a
options are mutually exclusive.
If multiple options are provided, the last one takes effect.
.
.SH EXIT STATUS
.TP
0
The operation completed successfully.
.TP
1
An error occurred.
.
.SH NOTES
.SS Availability on FreeBSD
By the time this manual is written, this program is not available on
stable releases of FreeBSD, since the latter does not yet support
.BR ioctl (2)
in its
.BR fusefs (5)
implementation.
.
.SH SEE ALSO
.BR fsck.bookmarkfs (1),
.BR mount.bookmarkfs (1),
.BR ioctl (2),
.BR readdir (3),
.BR fusefs (5)
.PP
The full BookmarkFS User Manual is maintained as a Texinfo document.
To read it locally, run:
.PP
.in +4n
.EX
.B info bookmarkfs
.EE
.in
.
.SH COPYRIGHT
Copyright (C) 2024  CismonX <admin@cismon.net>
.PP
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
.PP
You should have received a copy of the license along with this document.
If not, see <https://www.gnu.org/licenses/fdl-1.3.html>.
